## NumPy Quick Overview for absolute beginners

#### What is NumPy

###### NumPy is made of 2 words: Num for Numerical and Py for Python : or you can say this is an open source library used for Number values in python, used in the field of science and engineering. The core value of NumPy array is ndarray ( you can put any number in place of n, if you put 0-scalar, 1-1dimensional, 2-matrix, 3 and greater are tensors (PyTorch is another python library which deals with 3D arrays type of structures))

##### What is an array?

###### An array is considered as a space in grid which holds one element in per grid provided

##### Why do we use NumPy if we have Python List in place?

###### As we all know Python lists are quite faster but this contains a variety of data types elements into it and this is a kind of heterogeneous structure hence in order to return the result any operation can take time to sync the operation and revert to you, instead NumPy array are much faster than the traditional list of python as NumPy array have homogeneous kind of structure and it will take negligible time to revert you the answer, hence using NumPy array is the smartest way.

##### What are restriction do we have with NumPy array?

###### Following are restrictions we have with NumPy arrays:
###### 1. this holds homogeneous kind of structure meaning all elements of same kind
###### 2. once array created, you can't change the size of an array
###### 3. the shape of an array is rectangular

###### Throughout the NumPy documentation you will find this kind of code block
a=np.array([1,2,3,4,5])

##### Lets' install and import NumPy library

In [1]:
pip install numpy


[notice] A new release of pip is available: 24.1.1 -> 24.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

##### Let's create basic arrays

In [75]:
# simple method
# a=np.array([1,2,3,4,5,6,7,8,9,10])
# a=np.array([[1,2,3],[4,5,6]])
# a=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

# using numpy method
# a=np.zeros(5)
# a=np.zeros(3,4)
# a=np.zeros(3,4,dtype=np.int32)
# a=np.ones(5)
# a=np.ones(2,3)
# a=np.ones(2,3,dtype=np.int32)
# a=np.linspace(1,100)
# a=np.linspace(1,100,5)
# a=np.linspace(1,100,num=5)
# a=np.arange(10)
# a=np.arange(0,100)
# a=np.arange(0,100,2)
# a=np.eye(10,dtype=np.int8)
# a=np.empty(5)
# np.empty((5,5),dtype=np.int8)


##### Reading items / accessing items / updating items

In [63]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.array([[1,2,3],[4,5,6]])
print(a[0])
print(a[0:5])
print(a[:5])
print(a[2:])
print(x[0][-1])
print(x[-1][-3:-1])

np.take(a,[0,3,6]) # specific items to pick
np.put(a,[0,3,6],[10,10,10]) # update new values for specific items selected
a[:5:2] # Start at 1st through 5th with 2 step
x[:,1] # Get 2nd value from each row
x[::-1]# Flip Array

1
[1 2 3 4 5]
[1 2 3 4 5]
[ 3  4  5  6  7  8  9 10]
3
[4 5]


array([[4, 5, 6],
       [1, 2, 3]])

##### Copy / View

In [30]:
b=a.copy()
b[0]=100
b
a

b=a.view()
b[0]=100
b
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

##### Attributes

In [65]:
# attributes : ndim / size / shape / dtype
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

a.ndim,a.dtype
b.ndim,b.dtype
c.ndim,c.dtype

a.size, b.size, c.size
a.shape, b.shape, c.shape

# reshaping arrays
a.shape, a[np.newaxis,:].shape, a[:,np.newaxis].shape #1st method
a.resize((2,5)) #2nd method
np.expand_dims(c,axis=0).shape #3rd method


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

##### Getting help with any Numpy functions (use function?)


In [74]:
np.eye?

Signature:
np.eye(
    N,
    M=None,
    k=0,
    dtype=<class 'float'>,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference

##### Generating Random numbers

In [121]:
# np.random.random(5) # 5 random numbers generated
np.random.rand(1,10,2) # start from 1 till 10 in how many column (random numbers generated)
np.random.randint([8,5],[[10,10]]) # between 8 to 10 and 5 to 10 (random numbers generated)
np.random.randint(1,5) # between 1 to 5 (single random number generated)
np.random.randn(1,5) # start from 1 to 5 (random number generated)
np.random.random_integers(1,10,5) # start-end-size (random numbers generated)
np.random.random_sample((5,5)) #5 rows 5 columns (random numbers generated as sample)


/var/folders/4m/1npqh7l57tqg27ytqgrsj9n80000gn/T/ipykernel_1023/2227449520.py:6: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  np.random.random_integers(1,10,5) # start-end-size (random numbers generated)


array([[0.59987026, 0.82391422, 0.67795135, 0.58411054, 0.67001968],
       [0.24409989, 0.73388584, 0.5963192 , 0.14430244, 0.24687733],
       [0.74170657, 0.98752625, 0.72179529, 0.38593205, 0.4846573 ],
       [0.61957319, 0.15378683, 0.90084559, 0.27535595, 0.27049562],
       [0.51988568, 0.1494173 , 0.2583469 , 0.13661379, 0.99357239]])

##### Slicing | Indexing | Filtering

In [8]:
#suppose an array is a like
a=np.arange(0,100)
# i want all values >50
a[a>50]
# i want all values between 10 and 70
a[(a>=10) & (a<=70)]
# i want excluding above condition
a[~((a>=10) & (a<=70))]
# i want all even values
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

##### Sorting

In [11]:
#suppose an array is a like
a=np.arange(0,100)
np.sort(a) # ascending order
np.flip(a) # descending order

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

##### Unique | Transpose | Swapaxes | flatten | ravel

In [32]:
# suppose an array like b
b=np.array([10,23,23,23,45,4,4,3,2,1,10,10,10])
np.unique(b) # will show all unique values

# suppose an array like c
c=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
c # 3x5 matrix
np.transpose(c) # 5x3 matrix
c.T # 5x3 matrix

c.swapaxes(0,1) # work like transpose
c.flatten() # arrays got flat structure
c.ravel() # arrays got flat structure


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

##### Stacking | combining arrays | Splitting

In [15]:
#suppose arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
np.vstack((a,b))
np.hstack((a,b))

np.column_stack((a,b))
np.row_stack((a,b))

np.hsplit(a,(2,4))
x=np.arange(12)
np.hsplit(x,(3,4))

/var/folders/4m/1npqh7l57tqg27ytqgrsj9n80000gn/T/ipykernel_708/1717189221.py:8: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


[array([0, 1, 2]), array([3]), array([ 4,  5,  6,  7,  8,  9, 10, 11])]

##### Basic Maths opertions

In [38]:
print(x.sum())
print(x.max())
print(x.min())
print(x.mean())
print(x.std())
print(np.median(x))
# suppose we have arrays like
a=np.array([1,2,3])
b=np.array([4,5,6])

np.power(a,b)
np.sqrt(a), np.sqrt(b)
np.cbrt(a), np.cbrt(b)
np.exp(a)
np.log(a)
np.log2(a)
np.log10(a)

#suppose an array like p
p=np.arange(1,10)
p.cumsum()


print(np.lcm(12,15))
print(np.gcd(12,15))
print(np.floor(2.3))
print(np.ceil(2.3))
print(np.corrcoef(a))
np.percentile(a,[25,50,75])

66
11
0
5.5
3.452052529534663
5.5
60
3
2.0
3.0
1.0


array([1.5, 2. , 2.5])

##### Trigonometry functions

In [44]:
np.sin(a)
np.cos(a)
np.tan(a)
np.hypot(a,b)

array([4.12310563, 5.38516481, 6.70820393])